# Generated by Django 5.0 on 2024-01-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0005_uploadimage_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCTVImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cctv/images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='cctv/processed_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
