# Generated by Django 5.0 on 2025-12-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0007_cctvimage_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cctvimage',
            name='image',
            field=models.FileField(upload_to='cctv/images/'),
        ),
        migrations.AlterField(
            model_name='cctvimage',
            name='processed_image',
            field=models.FileField(blank=True, null=True, upload_to='cctv/processed_images/'),
        ),
    ]
